### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lollo26** [hungntt/xai_thyroid#11]
<img width="568" alt="Schermata 2024-02-29 alle 11 06 37" src="https://github.com/hungntt/xai_thyroid/assets/127774041/e2257afa-eb09-4c7b-99fc-82109c643f12">

Hi, I need some help. I have these two errors. The first when I install requirements.txt and the second in main with invalid syntax. How could I do? Thank you very much

**Comment by hungntt** [comment]
Hi, sorry because the initial code is not well supported and documented for MacOS:
- For the Keras version, you may loosen the package version such as keras~=2.2.4
- For the second problem, I am not pretty sure why there is an invalid syntax there (I tried on a Mac but it doesn't meet the same problem). May you debug the character ' there? I guess there is a character escape problem.

**Comment by lollo26** [comment]
Hi, thanks for your answer. For the first question i solved the problem. I tried with different editor like Visual Studio Code but the problem with the invalid syntax remains. Which editor did you use on your Mac? Thanks

**Comment by hungntt** [comment]
Hi, I use Pycharm on Mac. But I don't think the IDE is the problem, maybe you can use double quotation mark " instead?
